# -*- coding: utf-8 -*-
"""v1_GIFT4Rec_Baseline_Comparison_ML1M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTFStwNohnmxEb-X8S3dde0UkPktCj3u

# 🎯 GIFT4Rec vs Baseline Models - ML-1M Dataset**Baseline Models:** LightGCN, SGL, SimGCL, LightGCL, NCL, MeLU, KGAT, KGAT+DropoutNet

## 1. 📦 Installation
"""

!pip install torch-geometric scipy -qprint("✅ Installation completed!")

"""## 2. 📚 Import Libraries"""

import os
import random
import gc
import time
import copy
import json
import numpy as np
import pandas as pd
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm
from scipy.sparse import csr_matrix

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True

set_seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️ Device: {device}")

if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")

"""## 3. ⚙️ Configuration"""

CONFIG = {
    'embed_dim': 64, 'n_gnn_layers': 2, 'gat_heads': 4, 'hidden_dim': 128,
    'batch_size': 1024, 'lr': 0.001, 'weight_decay': 1e-5, 'epochs': 100,
    'dropout_rate': 0.2, 'neg_samples': 4, 'cl_temp': 0.2, 'cl_weight': 0.1,
    'aug_ratio': 0.1, 'active_ratio': 0.8, 'cold_ratio': 0.1, 'eval_freq': 10,
    'k_list': [10, 20, 50]
}
print("📋 Config loaded")

"""## 4. 📥 Data Loading"""

def download_ml1m(path='./ml-1m'):
    if not os.path.exists(path):
        import urllib.request, zipfile
        print("📥 Downloading...")
        urllib.request.urlretrieve("https://files.grouplens.org/datasets/movielens/ml-1m.zip", "ml-1m.zip")
        with zipfile.ZipFile("ml-1m.zip", 'r') as z: z.extractall('./')
        os.remove("ml-1m.zip")
    return path

def load_data(path):
    ratings = pd.read_csv(f'{path}/ratings.dat', sep='::', names=['user_id','item_id','rating','timestamp'], engine='python', encoding='latin-1')
    ratings = ratings[ratings['rating'] >= 4].sort_values(['user_id','timestamp'])
    users = pd.read_csv(f'{path}/users.dat', sep='::', names=['user_id','gender','age','occupation','zip'], engine='python', encoding='latin-1')
    movies = pd.read_csv(f'{path}/movies.dat', sep='::', names=['item_id','title','genres'], engine='python', encoding='latin-1')
    return ratings, users, movies

ratings, users, movies = load_data(download_ml1m())
print(f"📊 Ratings: {len(ratings):,}")

def prepare_data(ratings, users, movies):
    all_users, all_items = sorted(ratings['user_id'].unique()), sorted(ratings['item_id'].unique())
    u2i, i2i = {u: i for i, u in enumerate(all_users)}, {i: idx for idx, i in enumerate(all_items)}
    ratings = ratings.copy()
    ratings['uidx'], ratings['iidx'] = ratings['user_id'].map(u2i), ratings['item_id'].map(i2i)
    n_users, n_items = len(all_users), len(all_items)

    # User features
    users_f = users[users['user_id'].isin(all_users)].copy().set_index('user_id').loc[all_users].reset_index()
    users_f['g'], users_f['a'], users_f['o'] = users_f['gender'].map({'M':0,'F':1}), LabelEncoder().fit_transform(users_f['age']), LabelEncoder().fit_transform(users_f['occupation'])
    ng, na, no = 2, users_f['a'].nunique(), users_f['o'].nunique()
    user_feats = np.zeros((n_users, ng+na+no), dtype=np.float32)
    for i, (_, r) in enumerate(users_f.iterrows()):
        user_feats[i, r['g']], user_feats[i, ng+r['a']], user_feats[i, ng+na+r['o']] = 1, 1, 1

    # Item features
    all_genres = sorted(set(g for gs in movies['genres'] for g in gs.split('|')))
    genre2idx = {g: i for i, g in enumerate(all_genres)}
    movies_f = movies[movies['item_id'].isin(all_items)].copy()
    movies_f['iidx'] = movies_f['item_id'].map(i2i)
    item_feats = np.zeros((n_items, len(all_genres)), dtype=np.float32)
    for _, row in movies_f.iterrows():
        for g in row['genres'].split('|'): item_feats[row['iidx'], genre2idx[g]] = 1

    return ratings, n_users, n_items, torch.FloatTensor(user_feats), torch.FloatTensor(item_feats)

ratings, n_users, n_items, user_features, item_features = prepare_data(ratings, users, movies)
print(f"✅ Users: {n_users:,}, Items: {n_items:,}")

def split_users(ratings, ar=0.8, cr=0.1):
    counts = ratings.groupby('uidx').size().sort_values(ascending=False)
    n = len(counts)
    return set(counts.iloc[:int(n*ar)].index), set(counts.index) - set(counts.iloc[:int(n*ar)].index) - set(counts.iloc[-int(n*cr):].index), set(counts.iloc[-int(n*cr):].index)

def create_splits(ratings, active, warm, cold):
    train, val, ta, tw, tc = [], [], [], [], []
    for uid, g in ratings.groupby('uidx'):
        items = g['iidx'].tolist()
        if uid in active:
            if len(items)>=3:
                train.extend([(uid,i) for i in items[:-2]])
                val.append((uid,items[-2]))
                ta.append((uid,items[-1]))
            elif len(items)==2:
                train.append((uid,items[0]))
                ta.append((uid,items[1]))
            else:
                train.append((uid,items[0]))
        elif uid in warm:
            if len(items)>=2:
                train.extend([(uid,i) for i in items[:-1]])
                tw.append((uid,items[-1]))
            else:
                train.append((uid,items[0]))
        else:
            if items:
                tc.append((uid,items[0]))
    return {'train':train,'val':val,'test_active':ta,'test_warm':tw,'test_cold':tc}

active_users, warm_users, cold_users = split_users(ratings, CONFIG['active_ratio'], CONFIG['cold_ratio'])
splits = create_splits(ratings, active_users, warm_users, cold_users)
user_item_dict = defaultdict(list)
for u,i in splits['train']:
    user_item_dict[u].append(i)
print(f"👥 Active:{len(active_users):,} Warm:{len(warm_users):,} Cold:{len(cold_users):,}")
print(f"📂 Train:{len(splits['train']):,}")

"""## 5. 🏗️ Model Definitions"""

class LightGCNConv(nn.Module):
    def forward(self, x, e):
        r,c = e
        d = torch.bincount(r,minlength=x.size(0)).float().pow(-0.5)
        d[d==float('inf')]=0
        out = torch.zeros_like(x)
        out.index_add_(0,r,x[c]*(d[r]*d[c]).unsqueeze(-1))
        return out

class BaseGNN(nn.Module):
    def __init__(self,nu,ni,ed=64,nl=2):
        super().__init__()
        self.n_users,self.n_items=nu,ni
        self.user_emb,self.item_emb=nn.Embedding(nu,ed),nn.Embedding(ni,ed)
        self.convs=nn.ModuleList([LightGCNConv() for _ in range(nl)])
        nn.init.xavier_uniform_(self.user_emb.weight);nn.init.xavier_uniform_(self.item_emb.weight)

    def forward(self,e):
        x=torch.cat([self.user_emb.weight,self.item_emb.weight],0)
        all_e=[x]
        for c in self.convs: x=c(x,e);all_e.append(x)
        x=torch.stack(all_e,1).mean(1)
        return x[:self.n_users],x[self.n_users:]

def build_graph(data,nu,ni,dev):
    e=[]
    for u,i in data: e.append([u,nu+i]);e.append([nu+i,u])
    return torch.LongTensor(e).t().contiguous().to(dev)

class TrainDataset(Dataset):
    def __init__(s,d,ni,ui,nn=4): s.d,s.ni,s.ui,s.nn=d,ni,ui,nn

    def __len__(s): return len(s.d)

    def __getitem__(s,i):
        u,p=s.d[i];ps=set(s.ui.get(u,[]));n=[]
        while len(n)<s.nn:
            x=random.randint(0,s.ni-1)
            if x not in ps:n.append(x)
        return u,p,n

def collate_fn(b): return torch.LongTensor([x[0] for x in b]),torch.LongTensor([x[1] for x in b]),torch.LongTensor([x[2] for x in b])

print("✅ Base components")

class GIFT4Rec(nn.Module):
    def __init__(s,nu,ni,ufd,ed=64,nl=2,hd=128,dr=0.2):
        super().__init__()
        s.n_users,s.n_items,s.embed_dim,s.dr=nu,ni,ed,dr
        s.gnn=BaseGNN(nu,ni,ed,nl)
        s.side_enc=nn.Sequential(nn.Linear(ufd,ed*2),nn.LayerNorm(ed*2),nn.ReLU(),nn.Dropout(0.2),nn.Linear(ed*2,ed),nn.LayerNorm(ed))
        s.wg=nn.Sequential(nn.Linear(ed*2,hd),nn.LayerNorm(hd),nn.ReLU(),nn.Dropout(0.2),nn.Linear(hd,hd//2),nn.ReLU(),nn.Linear(hd//2,1),nn.Sigmoid())
        s.register_buffer('mean_emb',torch.zeros(ed))

    def update_mean(s,e,ids):
        with torch.no_grad():
            u,_=s.gnn(e)
            s.mean_emb=u[ids].mean(0)

    def fuse(s,b,si,do=True):
        a=s.wg(torch.cat([b,si],-1))
        if do and s.training:
            m=torch.rand(a.size(0),1,device=a.device)<s.dr
            return torch.where(m.expand_as(b),si,a*b+(1-a)*si),a
        return a*b+(1-a)*si,a

    def forward(s,e,uf,ui,pi,ni):
        ue,ie=s.gnn(e)
        se=s.side_enc(uf)
        ub,us,pe,ne=ue[ui],se[ui],ie[pi],ie[ni]
        fu,a=s.fuse(ub,us)
        ps,ns=(fu*pe).sum(-1),(fu.unsqueeze(1)*ne).sum(-1)
        bpr=-torch.log(torch.sigmoid(ps.unsqueeze(1)-ns)+1e-10).mean()
        l2=1e-5*(ub.norm(2).pow(2)+pe.norm(2).pow(2)+ne.norm(2).pow(2))/ui.size(0)
        return {'loss':bpr+l2,'bpr':bpr,'alpha':a.mean()}

    def predict(s,e,uf,ui,ic=None):
        s.eval()
        with torch.no_grad():
            ue,ie=s.gnn(e)
            se=s.side_enc(uf)
            ub,us=ue[ui],se[ui]
            if ic is not None and ic.any(): ub[ic]=s.mean_emb.expand(ic.sum(),-1)
            fu,_=s.fuse(ub,us,False)
            return torch.mm(fu,ie.t())

print("✅ GIFT4Rec")

class LightGCN(nn.Module):
    def __init__(s,nu,ni,ed=64,nl=2):
        super().__init__()
        s.n_users,s.n_items=nu,ni
        s.gnn=BaseGNN(nu,ni,ed,nl)

    def forward(s,e,ui,pi,ni):
        ue,ie=s.gnn(e)
        u,pe,ne=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne).sum(-1))+1e-10).mean()
        return {'loss':bpr+1e-5*(u.norm(2).pow(2)+pe.norm(2).pow(2)+ne.norm(2).pow(2))/ui.size(0),'bpr':bpr}

    def predict(s,e,ui):
        s.eval()
        with torch.no_grad():
            ue,ie=s.gnn(e)
            return torch.mm(ue[ui],ie.t())

print("✅ LightGCN")

class SGL(nn.Module):
    def __init__(s,nu,ni,ed=64,nl=2,ct=0.2,cw=0.1,ar=0.1):
        super().__init__()
        s.n_users,s.n_items,s.ct,s.cw,s.ar=nu,ni,ct,cw,ar
        s.gnn=BaseGNN(nu,ni,ed,nl)

    def aug(s,e): return e[:,torch.rand(e.size(1),device=e.device)>s.ar]

    def nce(s,z1,z2):
        z1,z2=F.normalize(z1,-1),F.normalize(z2,-1)
        return (-((z1*z2).sum(-1)/s.ct)+torch.logsumexp(torch.mm(z1,z2.t())/s.ct,1)).mean()

    def forward(s,e,ui,pi,ni):
        ue,ie=s.gnn(e);u,pe,ne=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne).sum(-1))+1e-10).mean()
        u1,i1=s.gnn(s.aug(e));u2,i2=s.gnn(s.aug(e))
        cl=(s.nce(u1[ui],u2[ui])+s.nce(i1[pi],i2[pi]))/2
        return {'loss':bpr+s.cw*cl+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr,'cl':cl}

    def predict(s,e,ui):
        s.eval()
        with torch.no_grad(): ue,ie=s.gnn(e);return torch.mm(ue[ui],ie.t())

print("✅ SGL")

class SimGCL(nn.Module):
    def __init__(s,nu,ni,ed=64,nl=2,ct=0.2,cw=0.1,ne=0.1):
        super().__init__()
        s.n_users,s.n_items,s.ct,s.cw,s.ne=nu,ni,ct,cw,ne
        s.gnn=BaseGNN(nu,ni,ed,nl)

    def noise(s,x): return x+torch.randn_like(x)*s.ne

    def nce(s,z1,z2):
        z1,z2=F.normalize(z1,-1),F.normalize(z2,-1)
        return (-((z1*z2).sum(-1)/s.ct)+torch.logsumexp(torch.mm(z1,z2.t())/s.ct,1)).mean()

    def forward(s,e,ui,pi,ni):
        ue,ie=s.gnn(e);u,pe,ne_=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne_).sum(-1))+1e-10).mean()
        cl=(s.nce(s.noise(ue)[ui],s.noise(ue)[ui])+s.nce(s.noise(ie)[pi],s.noise(ie)[pi]))/2
        return {'loss':bpr+s.cw*cl+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr,'cl':cl}

    def predict(s,e,ui):
        s.eval()
        with torch.no_grad(): ue,ie=s.gnn(e);return torch.mm(ue[ui],ie.t())

print("✅ SimGCL")

class LightGCL(nn.Module):
    def __init__(s,nu,ni,ed=64,nl=2,ct=0.2,cw=0.1,sq=5):
        super().__init__()
        s.n_users,s.n_items,s.ct,s.cw,s.sq=nu,ni,ct,cw,sq
        s.gnn=BaseGNN(nu,ni,ed,nl)
        s.svd_u=s.svd_v=None

    def compute_svd(s,e):
        from scipy.sparse.linalg import svds
        n=s.n_users+s.n_items;r,c=e.cpu().numpy()
        adj=csr_matrix((np.ones(len(r)),(r,c)),shape=(n,n))
        try:
            u,sv,vt=svds(adj.astype(np.float32),k=min(s.sq,min(adj.shape)-1))
            s.svd_u=torch.FloatTensor(u@np.diag(np.sqrt(sv))).to(e.device)
            s.svd_v=torch.FloatTensor(vt.T@np.diag(np.sqrt(sv))).to(e.device)
        except:pass

    def nce(s,z1,z2):
        z1,z2=F.normalize(z1,-1),F.normalize(z2,-1)
        return (-((z1*z2).sum(-1)/s.ct)+torch.logsumexp(torch.mm(z1,z2.t())/s.ct,1)).mean()

    def forward(s,e,ui,pi,ni):
        ue,ie=s.gnn(e);u,pe,ne_=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne_).sum(-1))+1e-10).mean()
        cl=torch.tensor(0.0,device=e.device)
        if s.svd_u is not None:
            try:cl=(s.nce(ue[ui],s.svd_u[:s.n_users][ui])+s.nce(ie[pi],s.svd_v[s.n_users:][pi]))/2
            except:pass
        return {'loss':bpr+s.cw*cl+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr,'cl':cl}

    def predict(s,e,ui):
        s.eval()
        with torch.no_grad(): ue,ie=s.gnn(e);return torch.mm(ue[ui],ie.t())

print("✅ LightGCL")

class NCL(nn.Module):
    def __init__(s,nu,ni,ed=64,nl=2,ct=0.2,cw=0.1,nc=100):
        super().__init__()
        s.n_users,s.n_items,s.ct,s.cw=nu,ni,ct,cw
        s.gnn=BaseGNN(nu,ni,ed,nl)
        s.uc=nn.Parameter(torch.randn(nc,ed)*0.1)
        s.ic=nn.Parameter(torch.randn(nc,ed)*0.1)

    def pcl(s,emb,cent,idx):
        e,c=F.normalize(emb[idx],-1),F.normalize(cent,-1)
        ass=F.softmax(torch.mm(F.normalize(emb,-1),c.t())/s.ct,-1)
        proto=F.normalize(torch.mm(ass[idx],c),-1)
        return (-((e*proto).sum(-1)/s.ct)+torch.logsumexp(torch.mm(e,c.t())/s.ct,1)).mean()

    def forward(s,e,ui,pi,ni):
        ue,ie=s.gnn(e);u,pe,ne_=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne_).sum(-1))+1e-10).mean()
        cl=(s.pcl(ue,s.uc,ui)+s.pcl(ie,s.ic,pi))/2
        return {'loss':bpr+s.cw*cl+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr,'cl':cl}

    def predict(s,e,ui):
        s.eval()
        with torch.no_grad(): ue,ie=s.gnn(e);return torch.mm(ue[ui],ie.t())

print("✅ NCL")

class MeLU(nn.Module):
    def __init__(s,nu,ni,ufd,ifd,ed=64,hd=128):
        super().__init__()
        s.n_users,s.n_items=nu,ni
        s.ue,s.ie=nn.Embedding(nu,ed),nn.Embedding(ni,ed)
        s.uenc=nn.Sequential(nn.Linear(ufd,hd),nn.ReLU(),nn.Linear(hd,ed))
        s.ienc=nn.Sequential(nn.Linear(ifd,hd),nn.ReLU(),nn.Linear(hd,ed))
        s.meta=nn.Sequential(nn.Linear(ed*4,hd),nn.ReLU(),nn.Dropout(0.2),nn.Linear(hd,ed),nn.ReLU())
        s.pred=nn.Linear(ed,1)
        nn.init.xavier_uniform_(s.ue.weight);nn.init.xavier_uniform_(s.ie.weight)

    def forward(s,ui,pi,ni,uf,itf):
        uc=torch.cat([s.ue(ui),s.uenc(uf[ui])],-1)
        pc=torch.cat([s.ie(pi),s.ienc(itf[pi])],-1)
        nc=torch.cat([s.ie(ni),s.ienc(itf[ni])],-1)
        ps=s.pred(s.meta(torch.cat([uc,pc],-1))).squeeze(-1)
        ue=uc.unsqueeze(1).expand(-1,ni.size(1),-1)
        ns=s.pred(s.meta(torch.cat([ue,nc],-1))).squeeze(-1)
        bpr=-torch.log(torch.sigmoid(ps.unsqueeze(1)-ns)+1e-10).mean()
        return {'loss':bpr+1e-5*s.ue(ui).norm(2).pow(2)/ui.size(0),'bpr':bpr}

    def predict(s,ui,uf,itf):
        s.eval()
        with torch.no_grad():
            uc=torch.cat([s.ue(ui),s.uenc(uf[ui])],-1)
            ic=torch.cat([s.ie.weight,s.ienc(itf)],-1)
            scores=[]
            for i in range(ui.size(0)):
                ue=uc[i:i+1].expand(s.n_items,-1)
                scores.append(s.pred(s.meta(torch.cat([ue,ic],-1))).squeeze(-1))
            return torch.stack(scores,0)

print("✅ MeLU")

class KGATConv(nn.Module):
    def __init__(s,ind,outd,nh=4,dr=0.1):
        super().__init__()
        s.nh,s.hd=nh,outd//nh
        s.W=nn.Linear(ind,outd,bias=False)
        s.a=nn.Parameter(torch.randn(nh,s.hd*2))
        s.dr=nn.Dropout(dr)
        s.lr=nn.LeakyReLU(0.2)
        nn.init.xavier_uniform_(s.W.weight);nn.init.xavier_uniform_(s.a)

    def forward(s,x,e):
        h=s.W(x).view(x.size(0),s.nh,s.hd)
        r,c=e
        hi,hj=h[r],h[c]
        att=(torch.cat([hi,hj],-1)*s.a.unsqueeze(0)).sum(-1)
        att=s.lr(att)
        em=torch.zeros(x.size(0),s.nh,device=x.device)
        em.index_reduce_(0,r,att,'amax',include_self=False)
        att=torch.exp(att-em[r])
        es=torch.zeros(x.size(0),s.nh,device=x.device)
        es.index_add_(0,r,att)
        att=s.dr(att/(es[r]+1e-10))
        out=torch.zeros(x.size(0),s.nh,s.hd,device=x.device)
        out.index_add_(0,r,hj*att.unsqueeze(-1))
        return out.view(x.size(0),-1)

class KGAT(nn.Module):
    def __init__(s,nu,ni,ifd,ed=64,nl=2,nh=4,dr=0.1):
        super().__init__()
        s.n_users,s.n_items=nu,ni
        s.ue,s.ie=nn.Embedding(nu,ed),nn.Embedding(ni,ed)
        s.ienc=nn.Linear(ifd,ed)
        s.convs=nn.ModuleList([KGATConv(ed,ed,nh,dr) for _ in range(nl)])
        nn.init.xavier_uniform_(s.ue.weight);nn.init.xavier_uniform_(s.ie.weight)

    def forward(s,e,itf,ui,pi,ni):
        ii=s.ie.weight+s.ienc(itf)
        x=torch.cat([s.ue.weight,ii],0)
        all_e=[x]
        for c in s.convs: x=F.elu(c(x,e));all_e.append(x)
        x=torch.stack(all_e,1).mean(1)
        ue,ie=x[:s.n_users],x[s.n_users:]
        u,pe,ne_=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne_).sum(-1))+1e-10).mean()
        return {'loss':bpr+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr}

    def predict(s,e,itf,ui):
        s.eval()
        with torch.no_grad():
            ii=s.ie.weight+s.ienc(itf)
            x=torch.cat([s.ue.weight,ii],0)
            for c in s.convs:x=F.elu(c(x,e))
            return torch.mm(x[:s.n_users][ui],x[s.n_users:].t())

print("✅ KGAT")

class KGATDropoutNet(nn.Module):
    def __init__(s,nu,ni,ufd,ifd,ed=64,nl=2,nh=4,dr=0.1,dnr=0.5):
        super().__init__()
        s.n_users,s.n_items,s.dnr=nu,ni,dnr
        s.ue,s.ie=nn.Embedding(nu,ed),nn.Embedding(ni,ed)
        s.ucont=nn.Sequential(nn.Linear(ufd,ed*2),nn.ReLU(),nn.Dropout(0.2),nn.Linear(ed*2,ed))
        s.icont=nn.Sequential(nn.Linear(ifd,ed*2),nn.ReLU(),nn.Dropout(0.2),nn.Linear(ed*2,ed))
        s.convs=nn.ModuleList([KGATConv(ed,ed,nh,dr) for _ in range(nl)])
        s.fuse=nn.Sequential(nn.Linear(ed*2,ed),nn.ReLU())
        nn.init.xavier_uniform_(s.ue.weight);nn.init.xavier_uniform_(s.ie.weight)

    def dn_aug(s,cf,cont):
        if s.training:
            m=torch.rand(cf.size(0),1,device=cf.device)<s.dnr
            return torch.where(m,cont,s.fuse(torch.cat([cf,cont],-1)))
        return s.fuse(torch.cat([cf,cont],-1))

    def get_emb(s,e,uf,itf):
        uc,ic=s.ucont(uf),s.icont(itf)
        ii=s.ie.weight+ic
        x=torch.cat([s.ue.weight,ii],0)
        all_e=[x]
        for c in s.convs:x=F.elu(c(x,e));all_e.append(x)
        x=torch.stack(all_e,1).mean(1)
        ucf,icf=x[:s.n_users],x[s.n_users:]
        return s.dn_aug(ucf,uc),s.dn_aug(icf,ic)

    def forward(s,e,uf,itf,ui,pi,ni):
        ue,ie=s.get_emb(e,uf,itf)
        u,pe,ne_=ue[ui],ie[pi],ie[ni]
        bpr=-torch.log(torch.sigmoid((u*pe).sum(-1).unsqueeze(1)-(u.unsqueeze(1)*ne_).sum(-1))+1e-10).mean()
        return {'loss':bpr+1e-5*(u.norm(2).pow(2))/ui.size(0),'bpr':bpr}

    def predict(s,e,uf,itf,ui):
        s.eval()
        with torch.no_grad():
            ue,ie=s.get_emb(e,uf,itf)
            return torch.mm(ue[ui],ie.t())

print("✅ KGAT+DropoutNet")

"""## 6. 🎓 Training & Evaluation"""

def evaluate(model, mname, edge, data, uid, cold, dev, uf=None, itf=None, ks=[10, 20, 50]):
    if not data:
        return {}
    model.eval()
    users, items = [d[0] for d in data], [d[1] for d in data]
    bs, metrics = 256, {f'{m}@{k}': [] for k in ks for m in ['R', 'HR', 'NDCG']}
    for st in range(0, len(users), bs):
        en = min(st + bs, len(users))
        bu, bi = users[st:en], items[st:en]
        ui, gt = torch.LongTensor(bu).to(dev), torch.LongTensor(bi).to(dev)
        ic = torch.BoolTensor([u in cold for u in bu]).to(dev)
        with torch.no_grad():
            if mname == 'GIFT4Rec':
                sc = model.predict(edge, uf, ui, ic if ic.any() else None)
            elif mname == 'MeLU':
                sc = model.predict(ui, uf, itf)
            elif mname == 'KGAT':
                sc = model.predict(edge, itf, ui)
            elif mname == 'KGAT_DropoutNet':
                sc = model.predict(edge, uf, itf, ui)
            else:
                sc = model.predict(edge, ui)
        for i, u in enumerate(bu):
            if u in uid:
                sc[i, uid[u]] = float('-inf')
        _, tk = torch.topk(sc, max(ks), 1)
        for k in ks:
            for i, (t, g) in enumerate(zip(tk[:, :k], gt)):
                h = (t == g).any().float().item()
                metrics[f'R@{k}'].append(h)
                metrics[f'HR@{k}'].append(h)
                if h:
                    metrics[f'NDCG@{k}'].append(1.0 / np.log2((t == g).nonzero(as_tuple=True)[0][0].item() + 2))
                else:
                    metrics[f'NDCG@{k}'].append(0.0)
    return {k: np.mean(v) * 100 for k, v in metrics.items()}

def train_model(model, mname, splits, edge, uid, cold, cfg, dev, uf=None, itf=None):
    model = model.to(dev)
    ds = TrainDataset(splits['train'], model.n_items, uid, cfg['neg_samples'])
    ld = DataLoader(ds, cfg['batch_size'], shuffle=True, collate_fn=collate_fn, num_workers=0)
    opt = torch.optim.AdamW(model.parameters(), lr=cfg['lr'], weight_decay=cfg['weight_decay'])
    sch = torch.optim.lr_scheduler.StepLR(opt, 20, 0.95)
    best_s, best_st = 0, None
    if mname == 'GIFT4Rec':
        nci = torch.LongTensor([u for u in range(model.n_users) if u not in cold]).to(dev)
    print(f"\n{'='*60}\n🚀 Training {mname}\n{'='*60}")
    for ep in range(1, cfg['epochs'] + 1):
        model.train()
        tl = 0
        for us, ps, ns in tqdm(ld, desc=f"Epoch {ep}", leave=False):
            us, ps, ns = us.to(dev), ps.to(dev), ns.to(dev)
            opt.zero_grad()
            if mname == 'GIFT4Rec':
                out = model(edge, uf, us, ps, ns)
            elif mname == 'MeLU':
                out = model(us, ps, ns, uf, itf)
            elif mname == 'KGAT':
                out = model(edge, itf, us, ps, ns)
            elif mname == 'KGAT_DropoutNet':
                out = model(edge, uf, itf, us, ps, ns)
            else:
                out = model(edge, us, ps, ns)
            out['loss'].backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            tl += out['loss'].item()
        if mname == 'LightGCL' and ep == 1:
            model.compute_svd(edge)
        sch.step()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        if ep % cfg['eval_freq'] == 0 or ep == 1:
            if mname == 'GIFT4Rec':
                model.update_mean(edge, nci)
            res = {}
            for n, d in [('active', splits['test_active']), ('warm', splits['test_warm']), ('cold', splits['test_cold'])]:
                if d:
                    res[n] = evaluate(model, mname, edge, d, uid, cold, dev, uf, itf, cfg['k_list'])
            if res:
                ov = {m: np.mean([res[s][m] for s in res if m in res.get(s, {})]) for m in ['R@10', 'R@20', 'R@50', 'HR@10', 'HR@20', 'HR@50', 'NDCG@10', 'NDCG@20', 'NDCG@50']}
                res['overall'] = ov
                if ov.get('NDCG@20', 0) > best_s:
                    best_s = ov['NDCG@20']
                    best_st = copy.deepcopy(model.state_dict())
                print(f"Ep{ep}: Loss={tl/len(ld):.4f} | Active R@20={res.get('active',{}).get('R@20',0):.2f} Cold R@20={res.get('cold',{}).get('R@20',0):.2f}")
    if best_st:
        model.load_state_dict(best_st)
    return model

def final_eval(model, mname, edge, splits, uid, cold, dev, uf=None, itf=None):
    if mname == 'GIFT4Rec':
        nci = torch.LongTensor([u for u in range(model.n_users) if u not in cold]).to(dev)
        model.update_mean(edge, nci)
    res = {}
    for n, d in [('active', splits['test_active']), ('warm', splits['test_warm']), ('cold', splits['test_cold'])]:
        if d:
            res[n] = evaluate(model, mname, edge, d, uid, cold, dev, uf, itf, CONFIG['k_list'])
    if res:
        ov = {m: np.mean([res[s][m] for s in res if m in res.get(s, {})]) for m in ['R@10', 'R@20', 'R@50', 'HR@10', 'HR@20', 'HR@50', 'NDCG@10', 'NDCG@20', 'NDCG@50']}
        res['overall'] = ov
    return res

print("✅ Training functions")

"""## 7. 🔬 Run Experiments"""

edge_index = build_graph(splits['train'], n_users, n_items, device)
user_feats_d = user_features.to(device)
item_feats_d = item_features.to(device)
print(f"📊 Graph: {edge_index.shape}")
all_results = {}
all_times = {}

"""### Train GIFT4Rec"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = GIFT4Rec(n_users, n_items, user_features.shape[1], CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['hidden_dim'], CONFIG['dropout_rate'])
m = train_model(m, 'GIFT4Rec', splits, edge_index, user_item_dict, cold_users, CONFIG, device, user_feats_d, item_feats_d)
all_results['GIFT4Rec'] = final_eval(m, 'GIFT4Rec', edge_index, splits, user_item_dict, cold_users, device, user_feats_d, item_feats_d)
all_times['GIFT4Rec'] = time.time() - t0
print(f"⏱️ GIFT4Rec: {all_times['GIFT4Rec']:.1f}s")

"""### Train LightGCN"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = LightGCN(n_users, n_items, CONFIG['embed_dim'], CONFIG['n_gnn_layers'])
m = train_model(m, 'LightGCN', splits, edge_index, user_item_dict, cold_users, CONFIG, device)
all_results['LightGCN'] = final_eval(m, 'LightGCN', edge_index, splits, user_item_dict, cold_users, device)
all_times['LightGCN'] = time.time() - t0
print(f"⏱️ LightGCN: {all_times['LightGCN']:.1f}s")

"""### Train SGL"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = SGL(n_users, n_items, CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['cl_temp'], CONFIG['cl_weight'], CONFIG['aug_ratio'])
m = train_model(m, 'SGL', splits, edge_index, user_item_dict, cold_users, CONFIG, device)
all_results['SGL'] = final_eval(m, 'SGL', edge_index, splits, user_item_dict, cold_users, device)
all_times['SGL'] = time.time() - t0
print(f"⏱️ SGL: {all_times['SGL']:.1f}s")

"""### Train SimGCL"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = SimGCL(n_users, n_items, CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['cl_temp'], CONFIG['cl_weight'], 0.1)
m = train_model(m, 'SimGCL', splits, edge_index, user_item_dict, cold_users, CONFIG, device)
all_results['SimGCL'] = final_eval(m, 'SimGCL', edge_index, splits, user_item_dict, cold_users, device)
all_times['SimGCL'] = time.time() - t0
print(f"⏱️ SimGCL: {all_times['SimGCL']:.1f}s")

"""### Train LightGCL"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = LightGCL(n_users, n_items, CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['cl_temp'], CONFIG['cl_weight'], 5)
m = train_model(m, 'LightGCL', splits, edge_index, user_item_dict, cold_users, CONFIG, device)
all_results['LightGCL'] = final_eval(m, 'LightGCL', edge_index, splits, user_item_dict, cold_users, device)
all_times['LightGCL'] = time.time() - t0
print(f"⏱️ LightGCL: {all_times['LightGCL']:.1f}s")

"""### Train NCL"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = NCL(n_users, n_items, CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['cl_temp'], CONFIG['cl_weight'], 100)
m = train_model(m, 'NCL', splits, edge_index, user_item_dict, cold_users, CONFIG, device)
all_results['NCL'] = final_eval(m, 'NCL', edge_index, splits, user_item_dict, cold_users, device)
all_times['NCL'] = time.time() - t0
print(f"⏱️ NCL: {all_times['NCL']:.1f}s")

"""### Train MeLU"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = MeLU(n_users, n_items, user_features.shape[1], item_features.shape[1], CONFIG['embed_dim'], CONFIG['hidden_dim'])
m = train_model(m, 'MeLU', splits, edge_index, user_item_dict, cold_users, CONFIG, device, user_feats_d, item_feats_d)
all_results['MeLU'] = final_eval(m, 'MeLU', edge_index, splits, user_item_dict, cold_users, device, user_feats_d, item_feats_d)
all_times['MeLU'] = time.time() - t0
print(f"⏱️ MeLU: {all_times['MeLU']:.1f}s")

"""### Train KGAT"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = KGAT(n_users, n_items, item_features.shape[1], CONFIG['embed_dim'], CONFIG['n_gnn_layers'], CONFIG['gat_heads'], CONFIG['dropout_rate'])
m = train_model(m, 'KGAT', splits, edge_index, user_item_dict, cold_users, CONFIG, device, user_feats_d, item_feats_d)
all_results['KGAT'] = final_eval(m, 'KGAT', edge_index, splits, user_item_dict, cold_users, device, user_feats_d, item_feats_d)
all_times['KGAT'] = time.time() - t0
print(f"⏱️ KGAT: {all_times['KGAT']:.1f}s")

"""### Train KGAT+DropoutNet"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
t0 = time.time()
m = KGATDropoutNet(n_users,n_items,user_features.shape[1],item_features.shape[1],CONFIG['embed_dim'],CONFIG['n_gnn_layers'],CONFIG['gat_heads'],CONFIG['dropout_rate'],0.5)
m = train_model(m,'KGAT_DropoutNet',splits,edge_index,user_item_dict,cold_users,CONFIG,device,user_feats_d,item_feats_d)
all_results['KGAT_DropoutNet'] = final_eval(m,'KGAT_DropoutNet',edge_index,splits,user_item_dict,cold_users,device,user_feats_d,item_feats_d)
all_times['KGAT+DropoutNet'] = time.time()-t0
print(f"⏱️ KGAT+DropoutNet: {all_times['KGAT+DropoutNet']:.1f}s")

"""## 8. 📈 Results"""

print("\n"+"="*100)
print("📊 FINAL RESULTS")
print("="*100)
print(f"\n{'Model':<18}|{'Set':<8}|{'R@10':>7}{'R@20':>7}{'R@50':>7}|{'NDCG@10':>8}{'NDCG@20':>8}{'NDCG@50':>8}")
print("-"*90)
for mn,res in all_results.items():
    for i,(sn,r) in enumerate(res.items()):
        if r:
            mc=mn if i==0 else ""
            print(f"{'⭐' if sn=='overall' else '  '}{mc:<16}|{sn.upper():<8}|{r.get('R@10',0):>7.2f}{r.get('R@20',0):>7.2f}{r.get('R@50',0):>7.2f}|{r.get('NDCG@10',0):>8.2f}{r.get('NDCG@20',0):>8.2f}{r.get('NDCG@50',0):>8.2f}")
    print("-"*90)

# Cold-start comparison
print("\n❄️ COLD-START COMPARISON")
cold_df=[]
for mn,res in all_results.items():
    if 'cold' in res and res['cold']:
        cold_df.append({'Model':mn,'R@20':res['cold'].get('R@20',0),'NDCG@20':res['cold'].get('NDCG@20',0)})
cold_df=sorted(cold_df,key=lambda x:-x['NDCG@20'])
for r in cold_df:
    print(f"  {r['Model']:<18}: R@20={r['R@20']:.2f}%, NDCG@20={r['NDCG@20']:.2f}%")
print(f"\n🏆 Best Cold-Start: {cold_df[0]['Model']}")

torch.save({'results':all_results,'times':all_times,'config':CONFIG},'experiment_results.pt')
print("\n✅ Results saved!")
print("\n🎯 EXPERIMENT COMPLETED!")