# -*- coding: utf-8 -*-
"""v1_GIFT4Rec_Fixed (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJKAl-Y4VXDuHduHFmwxTY1GN19nJmLk

# 🎯 GIFT4Rec: Cold-start Recommendation với Graph Neural Network

**Paper:** "GIFT4Rec: An effective side Information Fusion Technique apply to Graph neural network for cold-start recommendation" (ACIIDS 2023)

**Fixed Version** - Đã sửa lỗi memory và graph indexing

## 1. 📦 Cài đặt Dependencies
"""

!pip install torch-geometric -q
print("✅ Installation completed!")

"""## 2. 📚 Import Libraries"""

import os
import random
import numpy as np
import pandas as pd
from collections import defaultdict
from typing import Dict, List, Tuple
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm
import gc

# Set seeds
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True

set_seed(42)

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️ Device: {device}")
if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

"""## 3. ⚙️ Configuration (Optimized for Memory)"""

# Hyperparameters - Tối ưu cho memory và performance
CONFIG = {
    # Model architecture (giảm để fit memory)
    'embed_dim': 64,            # Embedding dimension
    'n_gnn_layers': 2,          # Số GNN layers
    'gat_heads': 4,             # Số attention heads
    'hidden_dim': 128,          # Hidden dim

    # Training
    'batch_size': 1024,
    'lr': 0.001,
    'weight_decay': 1e-5,
    'epochs': 100,

    # GIFT4Rec specific
    'dropout_rate': 0.2,
    'neg_samples': 4,

    # Data split
    'active_ratio': 0.8,
    'cold_ratio': 0.1,

    # Evaluation
    'eval_freq': 5,
}

print("📋 Configuration:")
for k, v in CONFIG.items():
    print(f"   {k}: {v}")

"""## 4. 📥 Download và Load Data"""

def download_ml1m(path='./ml-1m'):
    if not os.path.exists(path):
        import urllib.request, zipfile
        print("📥 Downloading MovieLens 1M...")
        url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
        urllib.request.urlretrieve(url, "ml-1m.zip")
        with zipfile.ZipFile("ml-1m.zip", 'r') as z:
            z.extractall('./')
        os.remove("ml-1m.zip")
        print("✅ Download completed!")
    else:
        print("✅ Dataset already exists!")
    return path

def load_data(path):
    ratings = pd.read_csv(f'{path}/ratings.dat', sep='::',
                          names=['user_id','item_id','rating','timestamp'],
                          engine='python', encoding='latin-1')
    ratings = ratings[ratings['rating'] >= 4].sort_values(['user_id','timestamp'])

    users = pd.read_csv(f'{path}/users.dat', sep='::',
                        names=['user_id','gender','age','occupation','zip'],
                        engine='python', encoding='latin-1')

    movies = pd.read_csv(f'{path}/movies.dat', sep='::',
                         names=['item_id','title','genres'],
                         engine='python', encoding='latin-1')

    return ratings, users, movies

data_path = download_ml1m()
ratings, users, movies = load_data(data_path)

print(f"\n📊 Dataset Statistics:")
print(f"   Ratings: {len(ratings):,}")
print(f"   Users: {len(users):,}")
print(f"   Movies: {len(movies):,}")

"""## 5. 🔧 Data Preprocessing"""

def prepare_data(ratings, users):
    """Encode IDs và tạo user features"""
    # Lấy unique users và items từ ratings
    all_users = sorted(ratings['user_id'].unique())
    all_items = sorted(ratings['item_id'].unique())

    # Tạo mapping liên tục từ 0
    u2i = {u: i for i, u in enumerate(all_users)}
    i2i = {i: idx for idx, i in enumerate(all_items)}

    ratings = ratings.copy()
    ratings['uidx'] = ratings['user_id'].map(u2i)
    ratings['iidx'] = ratings['item_id'].map(i2i)

    n_users = len(all_users)
    n_items = len(all_items)

    # User features
    users_filtered = users[users['user_id'].isin(all_users)].copy()
    users_filtered = users_filtered.set_index('user_id').loc[all_users].reset_index()

    users_filtered['g'] = users_filtered['gender'].map({'M': 0, 'F': 1})
    users_filtered['a'] = LabelEncoder().fit_transform(users_filtered['age'])
    users_filtered['o'] = LabelEncoder().fit_transform(users_filtered['occupation'])

    ng, na, no = 2, users_filtered['a'].nunique(), users_filtered['o'].nunique()
    feats = np.zeros((n_users, ng + na + no), dtype=np.float32)

    for i, (_, r) in enumerate(users_filtered.iterrows()):
        feats[i, r['g']] = 1
        feats[i, ng + r['a']] = 1
        feats[i, ng + na + r['o']] = 1

    return ratings, n_users, n_items, torch.FloatTensor(feats), u2i, i2i

ratings, n_users, n_items, user_features, u2i, i2i = prepare_data(ratings, users)

print(f"\n✅ Data prepared:")
print(f"   Users: {n_users:,}")
print(f"   Items: {n_items:,}")
print(f"   User feature dim: {user_features.shape[1]}")
print(f"   User idx range: 0 - {n_users-1}")
print(f"   Item idx range: 0 - {n_items-1}")

"""## 6. 📊 Split Users"""

def split_users(ratings, active_ratio=0.8, cold_ratio=0.1):
    counts = ratings.groupby('uidx').size().sort_values(ascending=False)
    n = len(counts)

    active = set(counts.iloc[:int(n*active_ratio)].index)
    cold = set(counts.iloc[-int(n*cold_ratio):].index)
    warm = set(counts.index) - active - cold

    return active, warm, cold

def create_splits(ratings, active, warm, cold):
    train, val, test_active, test_warm, test_cold = [], [], [], [], []

    for uid, g in ratings.groupby('uidx'):
        items = g['iidx'].tolist()

        if uid in active:
            if len(items) >= 3:
                train.extend([(uid, i) for i in items[:-2]])
                val.append((uid, items[-2]))
                test_active.append((uid, items[-1]))
            elif len(items) == 2:
                train.append((uid, items[0]))
                test_active.append((uid, items[1]))
            else:
                train.append((uid, items[0]))

        elif uid in warm:
            if len(items) >= 2:
                train.extend([(uid, i) for i in items[:-1]])
                test_warm.append((uid, items[-1]))
            else:
                train.append((uid, items[0]))

        else:  # cold
            if items:
                test_cold.append((uid, items[0]))

    return {
        'train': train, 'val': val,
        'test_active': test_active,
        'test_warm': test_warm,
        'test_cold': test_cold
    }

active_users, warm_users, cold_users = split_users(
    ratings, CONFIG['active_ratio'], CONFIG['cold_ratio']
)

print(f"\n👥 User Split:")
print(f"   Active: {len(active_users):,}")
print(f"   Warm: {len(warm_users):,}")
print(f"   Cold: {len(cold_users):,}")

splits = create_splits(ratings, active_users, warm_users, cold_users)

print(f"\n📂 Data Splits:")
for k, v in splits.items():
    print(f"   {k}: {len(v):,}")

"""## 7. 🔗 Build Graph (FIXED)"""

def get_user_items(data):
    """Tạo dict user -> list of items"""
    d = defaultdict(list)
    for u, i in data:
        d[u].append(i)
    return d

user_item_dict = get_user_items(splits['train'])

# Verify indices
all_train_users = set([x[0] for x in splits['train']])
all_train_items = set([x[1] for x in splits['train']])

print(f"\n🔗 Graph Info:")
print(f"   Training users: {len(all_train_users):,} (range: {min(all_train_users)} - {max(all_train_users)})")
print(f"   Training items: {len(all_train_items):,} (range: {min(all_train_items)} - {max(all_train_items)})")
print(f"   n_users: {n_users}, n_items: {n_items}")

"""## 8. 🏗️ Model Architecture (LightGCN-style, Memory Efficient)"""

class LightGCNConv(nn.Module):
    """Light Graph Convolution - memory efficient"""

    def __init__(self):
        super().__init__()

    def forward(self, x, edge_index, edge_weight=None):
        row, col = edge_index
        deg = torch.bincount(row, minlength=x.size(0)).float()
        deg_inv_sqrt = deg.pow(-0.5)
        deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # Sparse matrix multiplication
        out = torch.zeros_like(x)
        out.index_add_(0, row, x[col] * norm.unsqueeze(-1))

        return out


class GNNModule(nn.Module):
    """GNN module - LightGCN style for memory efficiency"""

    def __init__(self, n_users, n_items, embed_dim=64, n_layers=2):
        super().__init__()
        self.n_users = n_users
        self.n_items = n_items
        self.n_layers = n_layers
        self.embed_dim = embed_dim

        self.user_emb = nn.Embedding(n_users, embed_dim)
        self.item_emb = nn.Embedding(n_items, embed_dim)

        self.convs = nn.ModuleList([LightGCNConv() for _ in range(n_layers)])

        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

    def forward(self, edge_index):
        x = torch.cat([self.user_emb.weight, self.item_emb.weight], dim=0)
        all_emb = [x]

        for conv in self.convs:
            x = conv(x, edge_index)
            all_emb.append(x)

        x = torch.stack(all_emb, dim=1).mean(dim=1)

        return x[:self.n_users], x[self.n_users:]


class WeightGenerator(nn.Module):
    """Weight Generated Module"""

    def __init__(self, input_dim, hidden_dim=128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)


class SideInfoEncoder(nn.Module):
    """Encode user side information"""

    def __init__(self, input_dim, embed_dim):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, embed_dim * 2),
            nn.LayerNorm(embed_dim * 2),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(embed_dim * 2, embed_dim),
            nn.LayerNorm(embed_dim)
        )

    def forward(self, x):
        return self.encoder(x)

print("✅ Model components defined!")

class GIFT4Rec(nn.Module):
    """GIFT4Rec Model"""

    def __init__(self, n_users, n_items, user_feat_dim,
                 embed_dim=64, n_layers=2, hidden_dim=128, dropout=0.2):
        super().__init__()
        self.n_users = n_users
        self.n_items = n_items
        self.embed_dim = embed_dim
        self.dropout_rate = dropout

        self.gnn = GNNModule(n_users, n_items, embed_dim, n_layers)
        self.side_encoder = SideInfoEncoder(user_feat_dim, embed_dim)
        self.weight_gen = WeightGenerator(embed_dim * 2, hidden_dim)

        self.register_buffer('mean_user_emb', torch.zeros(embed_dim))

    def build_graph(self, train_data):
        """Build edge index from training data"""
        edges = []
        for u, i in train_data:
            # User node: u, Item node: n_users + i
            edges.append([u, self.n_users + i])
            edges.append([self.n_users + i, u])

        edge_index = torch.LongTensor(edges).t().contiguous()
        return edge_index

    def fuse_embeddings(self, behavior_emb, side_emb, use_dropout=True):
        concat = torch.cat([behavior_emb, side_emb], dim=-1)
        alpha = self.weight_gen(concat)

        if use_dropout and self.training:
            mask = torch.rand(alpha.size(0), 1, device=alpha.device) < self.dropout_rate
            final = torch.where(
                mask.expand_as(behavior_emb),
                side_emb,
                alpha * behavior_emb + (1 - alpha) * side_emb
            )
        else:
            final = alpha * behavior_emb + (1 - alpha) * side_emb

        return final, alpha

    def forward(self, edge_index, user_feats, user_ids, pos_items, neg_items):
        user_emb, item_emb = self.gnn(edge_index)
        side_emb = self.side_encoder(user_feats)

        u_behavior = user_emb[user_ids]
        u_side = side_emb[user_ids]
        pos_emb = item_emb[pos_items]
        neg_emb = item_emb[neg_items]

        final_u, alpha = self.fuse_embeddings(u_behavior, u_side, use_dropout=True)

        pos_scores = (final_u * pos_emb).sum(-1)
        neg_scores = (final_u.unsqueeze(1) * neg_emb).sum(-1)

        bpr_loss = -torch.log(torch.sigmoid(pos_scores.unsqueeze(1) - neg_scores) + 1e-10).mean()

        l2_reg = 1e-5 * (
            u_behavior.norm(2).pow(2) +
            pos_emb.norm(2).pow(2) +
            neg_emb.norm(2).pow(2)
        ) / user_ids.size(0)

        return {
            'loss': bpr_loss + l2_reg,
            'bpr': bpr_loss,
            'alpha': alpha.mean()
        }

    def compute_global_loss(self, edge_index, user_feats, val_users, val_items, item_emb_cache=None):
        with torch.no_grad():
            user_emb, item_emb = self.gnn(edge_index)
            side_emb = self.side_encoder(user_feats)

        u_behavior = user_emb[val_users]
        u_side = side_emb[val_users]

        # Sample items for efficiency
        n_sample = min(1000, item_emb.size(0))
        sample_idx = torch.randperm(item_emb.size(0))[:n_sample]
        item_emb_sample = item_emb[sample_idx]

        behavior_scores = torch.matmul(u_behavior, item_emb_sample.t())
        sideinfo_scores = torch.matmul(u_side, item_emb_sample.t())

        # Simple comparison: which gives higher score for target item
        target_beh_scores = (u_behavior * item_emb[val_items]).sum(-1)
        target_side_scores = (u_side * item_emb[val_items]).sum(-1)

        labels = (target_beh_scores > target_side_scores).float()

        concat = torch.cat([u_behavior, u_side], dim=-1)
        alpha = self.weight_gen(concat).squeeze()

        return F.binary_cross_entropy(alpha, labels)

    def update_mean_embedding(self, edge_index, non_cold_ids):
        with torch.no_grad():
            user_emb, _ = self.gnn(edge_index)
            self.mean_user_emb = user_emb[non_cold_ids].mean(0)

    def predict(self, edge_index, user_feats, user_ids, is_cold=None):
        self.eval()
        with torch.no_grad():
            user_emb, item_emb = self.gnn(edge_index)
            side_emb = self.side_encoder(user_feats)

            u_behavior = user_emb[user_ids]
            u_side = side_emb[user_ids]

            if is_cold is not None and is_cold.any():
                u_behavior = torch.where(
                    is_cold.unsqueeze(-1).expand_as(u_behavior),
                    self.mean_user_emb.expand_as(u_behavior),
                    u_behavior
                )

            final_u, _ = self.fuse_embeddings(u_behavior, u_side, use_dropout=False)
            return torch.matmul(final_u, item_emb.t())

print("✅ GIFT4Rec model defined!")

"""## 9. 📦 Dataset & Evaluation"""

class TrainDataset(Dataset):
    def __init__(self, data, n_items, user_items, n_neg=4):
        self.data = data
        self.n_items = n_items
        self.user_items = user_items
        self.n_neg = n_neg

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        user, pos = self.data[idx]
        pos_set = set(self.user_items.get(user, []))

        neg = []
        while len(neg) < self.n_neg:
            n = random.randint(0, self.n_items - 1)
            if n not in pos_set:
                neg.append(n)

        return user, pos, neg

def collate_fn(batch):
    users = torch.LongTensor([b[0] for b in batch])
    pos = torch.LongTensor([b[1] for b in batch])
    neg = torch.LongTensor([b[2] for b in batch])
    return users, pos, neg


def evaluate(model, edge_index, user_feats, test_data, user_items, cold_users, device, k_list=[10, 20, 50]):
    if not test_data:
        return {}

    model.eval()

    users = [d[0] for d in test_data]
    items = [d[1] for d in test_data]

    # Process in batches to save memory
    batch_size = 256
    all_metrics = {f'{m}@{k}': [] for k in k_list for m in ['R', 'HR', 'NDCG']}

    for start in range(0, len(users), batch_size):
        end = min(start + batch_size, len(users))
        batch_users = users[start:end]
        batch_items = items[start:end]

        user_ids = torch.LongTensor(batch_users).to(device)
        ground_truth = torch.LongTensor(batch_items).to(device)
        is_cold = torch.BoolTensor([u in cold_users for u in batch_users]).to(device)

        with torch.no_grad():
            scores = model.predict(edge_index, user_feats, user_ids,
                                  is_cold if is_cold.any() else None)

        # Mask training items
        for i, u in enumerate(batch_users):
            if u in user_items:
                scores[i, user_items[u]] = float('-inf')

        max_k = max(k_list)
        _, topk = torch.topk(scores, max_k, dim=1)

        for k in k_list:
            for i, (top, gt) in enumerate(zip(topk[:, :k], ground_truth)):
                hit = (top == gt).any().float().item()
                all_metrics[f'R@{k}'].append(hit)
                all_metrics[f'HR@{k}'].append(hit)

                if hit:
                    rank = (top == gt).nonzero(as_tuple=True)[0][0].item()
                    all_metrics[f'NDCG@{k}'].append(1.0 / np.log2(rank + 2))
                else:
                    all_metrics[f'NDCG@{k}'].append(0.0)

    return {k: np.mean(v) * 100 for k, v in all_metrics.items()}

print("✅ Dataset và Evaluation defined!")

"""## 10. 🚀 Training"""

def train_gift4rec(model, splits, user_feats, user_item_dict, cold_users, config, device):
    model = model.to(device)
    user_feats = user_feats.to(device)

    # Build graph
    edge_index = model.build_graph(splits['train']).to(device)
    print(f"   Edge index shape: {edge_index.shape}")
    print(f"   Edge index range: {edge_index.min().item()} - {edge_index.max().item()}")
    print(f"   Expected max: {model.n_users + model.n_items - 1}")

    # Dataset
    dataset = TrainDataset(splits['train'], model.n_items, user_item_dict, config['neg_samples'])
    loader = DataLoader(dataset, config['batch_size'], shuffle=True,
                       collate_fn=collate_fn, num_workers=0, pin_memory=True)

    # Optimizers
    optimizer = torch.optim.AdamW(model.parameters(), lr=config['lr'], weight_decay=config['weight_decay'])
    global_optimizer = torch.optim.Adam(model.weight_gen.parameters(), lr=config['lr'] * 0.1)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.95)

    non_cold_ids = torch.LongTensor([u for u in range(model.n_users) if u not in cold_users]).to(device)

    best_score = 0
    best_state = None

    print("\n" + "="*90)
    print("🚀 Training GIFT4Rec")
    print("="*90)

    for epoch in range(1, config['epochs'] + 1):
        model.train()
        total_loss, total_bpr, total_alpha = 0, 0, 0

        pbar = tqdm(loader, desc=f"Epoch {epoch}/{config['epochs']}", leave=False)
        for users, pos, neg in pbar:
            users = users.to(device)
            pos = pos.to(device)
            neg = neg.to(device)

            optimizer.zero_grad()
            outputs = model(edge_index, user_feats, users, pos, neg)
            outputs['loss'].backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += outputs['loss'].item()
            total_bpr += outputs['bpr'].item()
            total_alpha += outputs['alpha'].item()

            pbar.set_postfix({'loss': f"{outputs['loss'].item():.4f}"})

        # Global SIF
        if epoch % 3 == 0 and splits['val']:
            model.train()
            val_users = torch.LongTensor([v[0] for v in splits['val'][:500]]).to(device)
            val_items = torch.LongTensor([v[1] for v in splits['val'][:500]]).to(device)

            global_optimizer.zero_grad()
            global_loss = model.compute_global_loss(edge_index, user_feats, val_users, val_items)
            global_loss.backward()
            global_optimizer.step()

        scheduler.step()

        # Clear cache
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # Evaluate
        if epoch % config['eval_freq'] == 0 or epoch == 1:
            model.update_mean_embedding(edge_index, non_cold_ids)

            results = {}
            for name, data in [('active', splits['test_active']),
                              ('warm', splits['test_warm']),
                              ('cold', splits['test_cold'])]:
                if data:
                    results[name] = evaluate(model, edge_index, user_feats,
                                            data, user_item_dict, cold_users, device)

            if results:
                overall = {}
                for m in ['R@10','R@20','R@50','HR@10','HR@20','HR@50','NDCG@10','NDCG@20','NDCG@50']:
                    vals = [results[s][m] for s in results if m in results.get(s, {})]
                    if vals:
                        overall[m] = np.mean(vals)
                results['overall'] = overall

            n_batch = len(loader)
            print(f"\n📊 Epoch {epoch}/{config['epochs']}")
            print(f"   Loss: {total_loss/n_batch:.4f} | BPR: {total_bpr/n_batch:.4f} | Alpha: {total_alpha/n_batch:.4f}")

            print(f"\n   {'Set':<10} | {'R@10':>6} {'R@20':>6} {'R@50':>6} | "
                  f"{'HR@10':>6} {'HR@20':>6} {'HR@50':>6} | "
                  f"{'NDCG@10':>7} {'NDCG@20':>7} {'NDCG@50':>7}")
            print("   " + "-"*85)

            for name in ['active', 'warm', 'cold', 'overall']:
                if name in results:
                    r = results[name]
                    marker = "⭐" if name == 'overall' else "  "
                    print(f" {marker} {name.upper():<8} | {r['R@10']:>6.2f} {r['R@20']:>6.2f} {r['R@50']:>6.2f} | "
                          f"{r['HR@10']:>6.2f} {r['HR@20']:>6.2f} {r['HR@50']:>6.2f} | "
                          f"{r['NDCG@10']:>7.2f} {r['NDCG@20']:>7.2f} {r['NDCG@50']:>7.2f}")

            if 'overall' in results and results['overall'].get('R@50', 0) > best_score:
                best_score = results['overall']['R@50']
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                print(f"   ✅ New best! (R@50: {best_score:.2f})")

    if best_state:
        model.load_state_dict(best_state)
        model = model.to(device)

    return model, edge_index

print("✅ Training function defined!")

"""## 11. 🎯 Run Training"""

# Clear GPU memory
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()

# Create model
model = GIFT4Rec(
    n_users=n_users,
    n_items=n_items,
    user_feat_dim=user_features.shape[1],
    embed_dim=CONFIG['embed_dim'],
    n_layers=CONFIG['n_gnn_layers'],
    hidden_dim=CONFIG['hidden_dim'],
    dropout=CONFIG['dropout_rate']
)

total_params = sum(p.numel() for p in model.parameters())
print(f"\n🏗️ Model created: {total_params:,} parameters")

# Train
model, edge_index = train_gift4rec(
    model=model,
    splits=splits,
    user_feats=user_features,
    user_item_dict=user_item_dict,
    cold_users=cold_users,
    config=CONFIG,
    device=device
)

"""## 12. 📈 Final Evaluation"""

print("\n" + "="*90)
print("📈 FINAL RESULTS")
print("="*90)

user_feats_d = user_features.to(device)
non_cold_ids = torch.LongTensor([u for u in range(n_users) if u not in cold_users]).to(device)
model.update_mean_embedding(edge_index, non_cold_ids)

final_results = {}
for name, data in [('active', splits['test_active']),
                  ('warm', splits['test_warm']),
                  ('cold', splits['test_cold'])]:
    if data:
        final_results[name] = evaluate(model, edge_index, user_feats_d,
                                       data, user_item_dict, cold_users, device)

if final_results:
    overall = {}
    for m in ['R@10','R@20','R@50','HR@10','HR@20','HR@50','NDCG@10','NDCG@20','NDCG@50']:
        vals = [final_results[s][m] for s in final_results if m in final_results.get(s, {})]
        if vals:
            overall[m] = np.mean(vals)
    final_results['overall'] = overall

print(f"\n{'Set':<12} | {'R@10':>7} {'R@20':>7} {'R@50':>7} | "
      f"{'HR@10':>7} {'HR@20':>7} {'HR@50':>7} | "
      f"{'NDCG@10':>8} {'NDCG@20':>8} {'NDCG@50':>8}")
print("-"*95)

for name in ['active', 'warm', 'cold', 'overall']:
    if name in final_results:
        r = final_results[name]
        marker = "⭐" if name == 'overall' else "  "
        print(f"{marker}{name.upper():<10} | {r['R@10']:>7.2f} {r['R@20']:>7.2f} {r['R@50']:>7.2f} | "
              f"{r['HR@10']:>7.2f} {r['HR@20']:>7.2f} {r['HR@50']:>7.2f} | "
              f"{r['NDCG@10']:>8.2f} {r['NDCG@20']:>8.2f} {r['NDCG@50']:>8.2f}")

print("\n" + "="*90)
print("✅ Done!")

"""## 13. 💾 Save Model"""

torch.save({
    'model_state_dict': model.state_dict(),
    'config': CONFIG,
    'results': final_results
}, 'gift4rec_ml1m.pt')

print("✅ Model saved!")