# -*- coding: utf-8 -*-
"""v1_GIFT4Rec_Ablation_Study(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FGKMrak4VTM0O0d1os4vDyQpavI1ZEk3

# 🔬 GIFT4Rec Ablation Study

**Paper:** "GIFT4Rec: An effective side Information Fusion Technique apply to Graph neural network for cold-start recommendation" (ACIIDS 2023)

## Ablation Variants:
1. **Full GIFT4Rec** - Complete model với tất cả components
2. **w/o Side Information** - Không sử dụng side information (chỉ GNN)
3. **w/o Weight Generator** - Fusion cố định thay vì adaptive (α = 0.5)
4. **w/o GNN** - Chỉ sử dụng side information
5. **w/o Embedding Dropout** - Không dropout trong fusion
6. **w/o Global SIF** - Không sử dụng Global Side Information Fusion loss
7. **w/o Layer Aggregation** - Không mean aggregation các GNN layers

## 1. 📦 Installation
"""

!pip install torch-geometric -q
print("✅ Installation completed!")

"""## 2. 📚 Import Libraries"""

import os
import random
import numpy as np
import pandas as pd
from collections import defaultdict
from typing import Dict, List, Tuple, Optional
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm
import gc
import json
from datetime import datetime

# Set seeds
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True

set_seed(42)

# Device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"🖥️ Device: {device}")
if torch.cuda.is_available():
    print(f"   GPU: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

"""## 3. ⚙️ Configuration"""

CONFIG = {
    # Model architecture
    'embed_dim': 64,
    'n_gnn_layers': 2,
    'gat_heads': 4,
    'hidden_dim': 128,

    # Training
    'batch_size': 1024,
    'lr': 0.001,
    'weight_decay': 1e-5,
    'epochs': 100,

    # GIFT4Rec specific
    'dropout_rate': 0.2,
    'neg_samples': 4,

    # Data split
    'active_ratio': 0.8,
    'cold_ratio': 0.1,

    # Evaluation
    'eval_freq': 5,

    # Ablation specific
    'n_runs': 3,  # Số lần chạy để lấy mean và std
}

# Ablation configurations
ABLATION_CONFIGS = {
    'full': {
        'name': 'Full GIFT4Rec',
        'use_side_info': True,
        'use_weight_gen': True,
        'use_gnn': True,
        'use_dropout': True,
        'use_global_sif': True,
        'use_layer_agg': True,
    },
    'no_side': {
        'name': 'w/o Side Information',
        'use_side_info': False,
        'use_weight_gen': False,
        'use_gnn': True,
        'use_dropout': False,
        'use_global_sif': False,
        'use_layer_agg': True,
    },
    'no_weight_gen': {
        'name': 'w/o Weight Generator (α=0.5)',
        'use_side_info': True,
        'use_weight_gen': False,
        'use_gnn': True,
        'use_dropout': True,
        'use_global_sif': True,
        'use_layer_agg': True,
    },
    'no_gnn': {
        'name': 'w/o GNN (Side Info Only)',
        'use_side_info': True,
        'use_weight_gen': False,
        'use_gnn': False,
        'use_dropout': False,
        'use_global_sif': False,
        'use_layer_agg': False,
    },
    'no_dropout': {
        'name': 'w/o Embedding Dropout',
        'use_side_info': True,
        'use_weight_gen': True,
        'use_gnn': True,
        'use_dropout': False,
        'use_global_sif': True,
        'use_layer_agg': True,
    },
    'no_global_sif': {
        'name': 'w/o Global SIF Loss',
        'use_side_info': True,
        'use_weight_gen': True,
        'use_gnn': True,
        'use_dropout': True,
        'use_global_sif': False,
        'use_layer_agg': True,
    },
    'no_layer_agg': {
        'name': 'w/o Layer Aggregation',
        'use_side_info': True,
        'use_weight_gen': True,
        'use_gnn': True,
        'use_dropout': True,
        'use_global_sif': True,
        'use_layer_agg': False,
    },
}

print("📋 Base Configuration:")
for k, v in CONFIG.items():
    print(f"   {k}: {v}")

print(f"\n🔬 Ablation Variants: {len(ABLATION_CONFIGS)}")
for key, cfg in ABLATION_CONFIGS.items():
    print(f"   - {cfg['name']}")

"""## 4. 📥 Download và Load Data"""

def download_ml1m(path='./ml-1m'):
    if not os.path.exists(path):
        import urllib.request, zipfile
        print("📥 Downloading MovieLens 1M...")
        url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
        urllib.request.urlretrieve(url, "ml-1m.zip")
        with zipfile.ZipFile("ml-1m.zip", 'r') as z:
            z.extractall('./')
        os.remove("ml-1m.zip")
        print("✅ Download completed!")
    else:
        print("✅ Dataset already exists!")
    return path

def load_data(path):
    ratings = pd.read_csv(f'{path}/ratings.dat', sep='::',
                          names=['user_id','item_id','rating','timestamp'],
                          engine='python', encoding='latin-1')
    ratings = ratings[ratings['rating'] >= 4].sort_values(['user_id','timestamp'])

    users = pd.read_csv(f'{path}/users.dat', sep='::',
                        names=['user_id','gender','age','occupation','zip'],
                        engine='python', encoding='latin-1')

    movies = pd.read_csv(f'{path}/movies.dat', sep='::',
                         names=['item_id','title','genres'],
                         engine='python', encoding='latin-1')

    return ratings, users, movies

data_path = download_ml1m()
ratings, users, movies = load_data(data_path)

print(f"\n📊 Dataset Statistics:")
print(f"   Ratings: {len(ratings):,}")
print(f"   Users: {len(users):,}")
print(f"   Movies: {len(movies):,}")

"""## 5. 🔧 Data Preprocessing"""

def prepare_data(ratings, users):
    """Encode IDs và tạo user features"""
    all_users = sorted(ratings['user_id'].unique())
    all_items = sorted(ratings['item_id'].unique())

    u2i = {u: i for i, u in enumerate(all_users)}
    i2i = {i: idx for idx, i in enumerate(all_items)}

    ratings = ratings.copy()
    ratings['uidx'] = ratings['user_id'].map(u2i)
    ratings['iidx'] = ratings['item_id'].map(i2i)

    n_users = len(all_users)
    n_items = len(all_items)

    # User features
    users = users[users['user_id'].isin(all_users)].copy()
    users['uidx'] = users['user_id'].map(u2i)

    gender_enc = pd.get_dummies(users['gender'], prefix='g')
    age_enc = pd.get_dummies(users['age'], prefix='a')
    occ_enc = pd.get_dummies(users['occupation'], prefix='o')

    user_feat_df = pd.concat([users[['uidx']], gender_enc, age_enc, occ_enc], axis=1)
    user_feat_df = user_feat_df.sort_values('uidx')

    feat_cols = [c for c in user_feat_df.columns if c != 'uidx']
    user_feats = torch.FloatTensor(user_feat_df[feat_cols].values)

    return ratings, n_users, n_items, user_feats

ratings, n_users, n_items, user_feats = prepare_data(ratings, users)

print(f"\n✅ Data prepared:")
print(f"   Users: {n_users:,}")
print(f"   Items: {n_items:,}")
print(f"   User feature dim: {user_feats.shape[1]}")

"""## 6. 📊 Data Splitting"""

def create_user_item_dict(ratings):
    user_items = defaultdict(list)
    for _, row in ratings.iterrows():
        user_items[row['uidx']].append(row['iidx'])
    return dict(user_items)

def split_data(ratings, user_items, active_ratio=0.8, cold_ratio=0.1):
    users = sorted(user_items.keys())
    n = len(users)
    random.shuffle(users)

    n_active = int(n * active_ratio)
    n_cold = int(n * cold_ratio)

    active_users = set(users[:n_active])
    cold_users = set(users[n_active:n_active+n_cold])
    warm_users = set(users[n_active+n_cold:])

    train, val, test_active, test_warm, test_cold = [], [], [], [], []

    for u, items in user_items.items():
        if len(items) < 2:
            train.extend([(u, i) for i in items])
            continue

        if u in active_users:
            train.extend([(u, i) for i in items[:-2]])
            val.append((u, items[-2]))
            test_active.append((u, items[-1]))
        elif u in cold_users:
            test_cold.append((u, items[-1]))
        else:
            train.extend([(u, i) for i in items[:-1]])
            test_warm.append((u, items[-1]))

    return {
        'train': train,
        'val': val,
        'test_active': test_active,
        'test_warm': test_warm,
        'test_cold': test_cold,
    }, cold_users

user_item_dict = create_user_item_dict(ratings)
splits, cold_users = split_data(ratings, user_item_dict, CONFIG['active_ratio'], CONFIG['cold_ratio'])

print(f"\n📊 Data Splits:")
print(f"   Train: {len(splits['train']):,}")
print(f"   Val: {len(splits['val']):,}")
print(f"   Test Active: {len(splits['test_active']):,}")
print(f"   Test Warm: {len(splits['test_warm']):,}")
print(f"   Test Cold: {len(splits['test_cold']):,}")
print(f"   Cold Users: {len(cold_users):,}")

"""## 7. 🧠 Model Components"""

class LightGCNConv(nn.Module):
    """Light Graph Convolution"""

    def __init__(self):
        super().__init__()

    def forward(self, x, edge_index, edge_weight=None):
        row, col = edge_index
        deg = torch.bincount(row, minlength=x.size(0)).float()
        deg_inv_sqrt = deg.pow(-0.5)
        deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0

        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        out = torch.zeros_like(x)
        out.index_add_(0, row, x[col] * norm.unsqueeze(-1))

        return out


class GNNModule(nn.Module):
    """GNN module with optional layer aggregation"""

    def __init__(self, n_users, n_items, embed_dim=64, n_layers=2, use_layer_agg=True):
        super().__init__()
        self.n_users = n_users
        self.n_items = n_items
        self.n_layers = n_layers
        self.embed_dim = embed_dim
        self.use_layer_agg = use_layer_agg

        self.user_emb = nn.Embedding(n_users, embed_dim)
        self.item_emb = nn.Embedding(n_items, embed_dim)

        self.convs = nn.ModuleList([LightGCNConv() for _ in range(n_layers)])

        nn.init.xavier_uniform_(self.user_emb.weight)
        nn.init.xavier_uniform_(self.item_emb.weight)

    def forward(self, edge_index):
        x = torch.cat([self.user_emb.weight, self.item_emb.weight], dim=0)

        if self.use_layer_agg:
            all_emb = [x]
            for conv in self.convs:
                x = conv(x, edge_index)
                all_emb.append(x)
            x = torch.stack(all_emb, dim=1).mean(dim=1)
        else:
            # Only use final layer output
            for conv in self.convs:
                x = conv(x, edge_index)

        return x[:self.n_users], x[self.n_users:]


class WeightGenerator(nn.Module):
    """Adaptive weight generator for embedding fusion"""

    def __init__(self, input_dim, hidden_dim=128):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)


class SideInfoEncoder(nn.Module):
    """Encode user side information"""

    def __init__(self, input_dim, embed_dim):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, embed_dim * 2),
            nn.LayerNorm(embed_dim * 2),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(embed_dim * 2, embed_dim),
            nn.LayerNorm(embed_dim)
        )

    def forward(self, x):
        return self.encoder(x)

print("✅ Model components defined!")

"""## 8. 🎯 GIFT4Rec Model with Ablation Support"""

class GIFT4RecAblation(nn.Module):
    """GIFT4Rec Model with Ablation Study Support"""

    def __init__(self, n_users, n_items, user_feat_dim,
                 embed_dim=64, n_layers=2, hidden_dim=128, dropout=0.2,
                 ablation_config=None):
        super().__init__()

        # Default ablation config (full model)
        if ablation_config is None:
            ablation_config = ABLATION_CONFIGS['full']

        self.ablation = ablation_config
        self.n_users = n_users
        self.n_items = n_items
        self.embed_dim = embed_dim
        self.dropout_rate = dropout

        # GNN Module (optional)
        if self.ablation['use_gnn']:
            self.gnn = GNNModule(n_users, n_items, embed_dim, n_layers,
                                self.ablation['use_layer_agg'])
        else:
            self.gnn = None
            # Fallback item embeddings when no GNN
            self.item_emb = nn.Embedding(n_items, embed_dim)
            nn.init.xavier_uniform_(self.item_emb.weight)

        # Side Information Encoder (optional)
        if self.ablation['use_side_info']:
            self.side_encoder = SideInfoEncoder(user_feat_dim, embed_dim)
        else:
            self.side_encoder = None

        # Weight Generator (optional)
        if self.ablation['use_weight_gen'] and self.ablation['use_gnn'] and self.ablation['use_side_info']:
            self.weight_gen = WeightGenerator(embed_dim * 2, hidden_dim)
        else:
            self.weight_gen = None

        self.register_buffer('mean_user_emb', torch.zeros(embed_dim))

    def build_graph(self, train_data):
        """Build edge index from training data"""
        edges = []
        for u, i in train_data:
            edges.append([u, self.n_users + i])
            edges.append([self.n_users + i, u])
        edge_index = torch.LongTensor(edges).t().contiguous()
        return edge_index

    def get_user_embedding(self, user_emb_gnn, side_emb, use_dropout=True):
        """Get final user embedding based on ablation config"""

        # Case 1: No side info - use only GNN embedding
        if not self.ablation['use_side_info']:
            return user_emb_gnn, torch.ones(user_emb_gnn.size(0), 1, device=user_emb_gnn.device)

        # Case 2: No GNN - use only side info embedding
        if not self.ablation['use_gnn']:
            return side_emb, torch.zeros(side_emb.size(0), 1, device=side_emb.device)

        # Case 3: Both available - fuse them
        if self.ablation['use_weight_gen']:
            # Adaptive fusion with weight generator
            concat = torch.cat([user_emb_gnn, side_emb], dim=-1)
            alpha = self.weight_gen(concat)
        else:
            # Fixed fusion (α = 0.5)
            alpha = torch.full((user_emb_gnn.size(0), 1), 0.5, device=user_emb_gnn.device)

        # Apply dropout if enabled
        if self.ablation['use_dropout'] and use_dropout and self.training:
            mask = torch.rand(alpha.size(0), 1, device=alpha.device) < self.dropout_rate
            final = torch.where(
                mask.expand_as(user_emb_gnn),
                side_emb,
                alpha * user_emb_gnn + (1 - alpha) * side_emb
            )
        else:
            final = alpha * user_emb_gnn + (1 - alpha) * side_emb

        return final, alpha

    def forward(self, edge_index, user_feats, user_ids, pos_items, neg_items):
        # Get embeddings
        if self.ablation['use_gnn']:
            user_emb, item_emb = self.gnn(edge_index)
            u_behavior = user_emb[user_ids]
        else:
            u_behavior = None
            item_emb = self.item_emb.weight

        if self.ablation['use_side_info']:
            side_emb_all = self.side_encoder(user_feats)
            u_side = side_emb_all[user_ids]
        else:
            u_side = None

        # Get final user embedding
        if u_behavior is not None and u_side is not None:
            final_u, alpha = self.get_user_embedding(u_behavior, u_side, use_dropout=True)
        elif u_behavior is not None:
            final_u, alpha = u_behavior, torch.ones(u_behavior.size(0), 1, device=u_behavior.device)
        else:
            final_u, alpha = u_side, torch.zeros(u_side.size(0), 1, device=u_side.device)

        pos_emb = item_emb[pos_items]
        neg_emb = item_emb[neg_items]

        pos_scores = (final_u * pos_emb).sum(-1)
        neg_scores = (final_u.unsqueeze(1) * neg_emb).sum(-1)

        bpr_loss = -torch.log(torch.sigmoid(pos_scores.unsqueeze(1) - neg_scores) + 1e-10).mean()

        # L2 regularization
        l2_reg = 1e-5 * (
            final_u.norm(2).pow(2) +
            pos_emb.norm(2).pow(2) +
            neg_emb.norm(2).pow(2)
        ) / user_ids.size(0)

        return {
            'loss': bpr_loss + l2_reg,
            'bpr': bpr_loss,
            'alpha': alpha.mean()
        }

    def compute_global_loss(self, edge_index, user_feats, val_users, val_items, item_emb_cache=None):
        """Global SIF loss (only if enabled)"""
        if not self.ablation['use_global_sif']:
            return torch.tensor(0.0, device=val_users.device)

        if not self.ablation['use_gnn'] or not self.ablation['use_side_info']:
            return torch.tensor(0.0, device=val_users.device)

        with torch.no_grad():
            user_emb, item_emb = self.gnn(edge_index)
            side_emb = self.side_encoder(user_feats)

        u_behavior = user_emb[val_users]
        u_side = side_emb[val_users]

        n_sample = min(1000, item_emb.size(0))
        sample_idx = torch.randperm(item_emb.size(0), device=item_emb.device)[:n_sample]
        item_sample = item_emb[sample_idx]

        final_u, alpha = self.get_user_embedding(u_behavior, u_side, use_dropout=False)

        scores = torch.mm(final_u, item_sample.t())
        targets = (sample_idx.unsqueeze(0) == val_items.unsqueeze(1)).float().to(scores.device)

        loss = F.binary_cross_entropy_with_logits(scores, targets)
        return loss

    def update_mean_embedding(self, edge_index, non_cold_ids):
        """Update mean user embedding for cold-start"""
        if not self.ablation['use_gnn']:
            return

        with torch.no_grad():
            user_emb, _ = self.gnn(edge_index)
            self.mean_user_emb = user_emb[non_cold_ids].mean(dim=0)

    def predict(self, edge_index, user_feats, user_ids, is_cold=None):
        """Predict scores for evaluation"""
        with torch.no_grad():
            if self.ablation['use_gnn']:
                user_emb, item_emb = self.gnn(edge_index)
            else:
                user_emb = None
                item_emb = self.item_emb.weight

            if self.ablation['use_side_info']:
                side_emb = self.side_encoder(user_feats)
            else:
                side_emb = None

            if user_emb is not None:
                u_behavior = user_emb[user_ids]
            else:
                u_behavior = None

            if side_emb is not None:
                u_side = side_emb[user_ids]
            else:
                u_side = None

            # Handle cold users
            if is_cold is not None and is_cold.any() and u_behavior is not None:
                u_behavior[is_cold] = self.mean_user_emb

            # Get final embedding
            if u_behavior is not None and u_side is not None:
                final_u, _ = self.get_user_embedding(u_behavior, u_side, use_dropout=False)
            elif u_behavior is not None:
                final_u = u_behavior
            else:
                final_u = u_side

            scores = torch.mm(final_u, item_emb.t())
            return scores

print("✅ GIFT4RecAblation model defined!")

"""## 9. 📊 Training Utilities"""

class TrainDataset(Dataset):
    def __init__(self, data, n_items, user_items, n_neg=4):
        self.data = data
        self.n_items = n_items
        self.user_items = user_items
        self.n_neg = n_neg

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        user, pos = self.data[idx]
        pos_set = set(self.user_items.get(user, []))

        neg = []
        while len(neg) < self.n_neg:
            n = random.randint(0, self.n_items - 1)
            if n not in pos_set:
                neg.append(n)

        return user, pos, neg

def collate_fn(batch):
    users = torch.LongTensor([b[0] for b in batch])
    pos = torch.LongTensor([b[1] for b in batch])
    neg = torch.LongTensor([b[2] for b in batch])
    return users, pos, neg


def evaluate(model, edge_index, user_feats, test_data, user_items, cold_users, device, k_list=[10, 20, 50]):
    if not test_data:
        return {}

    model.eval()

    users = [d[0] for d in test_data]
    items = [d[1] for d in test_data]

    batch_size = 256
    all_metrics = {f'{m}@{k}': [] for k in k_list for m in ['R', 'HR', 'NDCG']}

    for start in range(0, len(users), batch_size):
        end = min(start + batch_size, len(users))
        batch_users = users[start:end]
        batch_items = items[start:end]

        user_ids = torch.LongTensor(batch_users).to(device)
        ground_truth = torch.LongTensor(batch_items).to(device)
        is_cold = torch.BoolTensor([u in cold_users for u in batch_users]).to(device)

        with torch.no_grad():
            scores = model.predict(edge_index, user_feats, user_ids,
                                  is_cold if is_cold.any() else None)

        # Mask training items
        for i, u in enumerate(batch_users):
            if u in user_items:
                scores[i, user_items[u]] = float('-inf')

        max_k = max(k_list)
        _, topk = torch.topk(scores, max_k, dim=1)

        for k in k_list:
            for i, (top, gt) in enumerate(zip(topk[:, :k], ground_truth)):
                hit = (top == gt).any().float().item()
                all_metrics[f'R@{k}'].append(hit)
                all_metrics[f'HR@{k}'].append(hit)

                if hit:
                    rank = (top == gt).nonzero(as_tuple=True)[0][0].item()
                    all_metrics[f'NDCG@{k}'].append(1.0 / np.log2(rank + 2))
                else:
                    all_metrics[f'NDCG@{k}'].append(0.0)

    return {k: np.mean(v) * 100 for k, v in all_metrics.items()}

print("✅ Training utilities defined!")

"""## 10. 🚀 Training Function for Ablation"""

def train_ablation_variant(ablation_key, ablation_config, splits, user_feats, user_item_dict,
                          cold_users, n_users, n_items, config, device, verbose=True):
    """Train a single ablation variant"""

    model = GIFT4RecAblation(
        n_users=n_users,
        n_items=n_items,
        user_feat_dim=user_feats.shape[1],
        embed_dim=config['embed_dim'],
        n_layers=config['n_gnn_layers'],
        hidden_dim=config['hidden_dim'],
        dropout=config['dropout_rate'],
        ablation_config=ablation_config
    ).to(device)

    user_feats_device = user_feats.to(device)

    # Build graph
    edge_index = model.build_graph(splits['train']).to(device)

    # Dataset
    dataset = TrainDataset(splits['train'], n_items, user_item_dict, config['neg_samples'])
    loader = DataLoader(dataset, config['batch_size'], shuffle=True,
                       collate_fn=collate_fn, num_workers=0, pin_memory=True)

    # Optimizers
    optimizer = torch.optim.AdamW(model.parameters(), lr=config['lr'], weight_decay=config['weight_decay'])

    if model.weight_gen is not None:
        global_optimizer = torch.optim.Adam(model.weight_gen.parameters(), lr=config['lr'] * 0.1)
    else:
        global_optimizer = None

    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.95)

    non_cold_ids = torch.LongTensor([u for u in range(n_users) if u not in cold_users]).to(device)

    best_score = 0
    best_results = None

    for epoch in range(1, config['epochs'] + 1):
        model.train()
        total_loss = 0

        pbar = tqdm(loader, desc=f"Epoch {epoch}/{config['epochs']}", leave=False, disable=not verbose)
        for users, pos, neg in pbar:
            users = users.to(device)
            pos = pos.to(device)
            neg = neg.to(device)

            optimizer.zero_grad()
            outputs = model(edge_index, user_feats_device, users, pos, neg)
            outputs['loss'].backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            total_loss += outputs['loss'].item()
            pbar.set_postfix({'loss': f"{outputs['loss'].item():.4f}"})

        # Global SIF (if applicable)
        if ablation_config['use_global_sif'] and global_optimizer is not None and epoch % 3 == 0 and splits['val']:
            model.train()
            val_users = torch.LongTensor([v[0] for v in splits['val'][:500]]).to(device)
            val_items = torch.LongTensor([v[1] for v in splits['val'][:500]]).to(device)

            global_optimizer.zero_grad()
            global_loss = model.compute_global_loss(edge_index, user_feats_device, val_users, val_items)
            if global_loss.item() > 0:
                global_loss.backward()
                global_optimizer.step()

        scheduler.step()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # Evaluate periodically
        if epoch % config['eval_freq'] == 0 or epoch == config['epochs']:
            model.update_mean_embedding(edge_index, non_cold_ids)

            results = {}
            for name, data in [('active', splits['test_active']),
                              ('warm', splits['test_warm']),
                              ('cold', splits['test_cold'])]:
                if data:
                    results[name] = evaluate(model, edge_index, user_feats_device,
                                            data, user_item_dict, cold_users, device)

            if results:
                overall = {}
                for m in ['R@10','R@20','R@50','HR@10','HR@20','HR@50','NDCG@10','NDCG@20','NDCG@50']:
                    vals = [results[s][m] for s in results if m in results.get(s, {})]
                    if vals:
                        overall[m] = np.mean(vals)
                results['overall'] = overall

                # Track best based on overall NDCG@10
                current_score = overall.get('NDCG@10', 0)
                if current_score > best_score:
                    best_score = current_score
                    best_results = results.copy()

    # Clean up
    del model, optimizer, scheduler
    if global_optimizer:
        del global_optimizer
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return best_results

print("✅ Training function defined!")

"""## 11. 🔬 Run Ablation Study"""

def run_ablation_study(ablation_configs, splits, user_feats, user_item_dict,
                       cold_users, n_users, n_items, config, device, n_runs=3):
    """Run complete ablation study with multiple runs"""

    all_results = {}

    print("="*100)
    print("🔬 GIFT4Rec ABLATION STUDY")
    print("="*100)
    print(f"   Number of variants: {len(ablation_configs)}")
    print(f"   Runs per variant: {n_runs}")
    print(f"   Total experiments: {len(ablation_configs) * n_runs}")
    print("="*100 + "\n")

    for variant_key, variant_config in ablation_configs.items():
        print(f"\n{'='*80}")
        print(f"📊 Running: {variant_config['name']}")
        print(f"{'='*80}")
        print(f"   Config: {variant_config}")

        variant_results = []

        for run_id in range(n_runs):
            print(f"\n   🏃 Run {run_id + 1}/{n_runs}")
            set_seed(42 + run_id)  # Different seed for each run

            # Re-split data for each run
            splits_run, cold_users_run = split_data(ratings, user_item_dict,
                                                    config['active_ratio'],
                                                    config['cold_ratio'])

            results = train_ablation_variant(
                variant_key, variant_config,
                splits_run, user_feats, user_item_dict,
                cold_users_run, n_users, n_items, config, device,
                verbose=(run_id == 0)  # Only show progress for first run
            )

            variant_results.append(results)

            if results:
                print(f"      Overall NDCG@10: {results['overall'].get('NDCG@10', 0):.2f}%")

        # Aggregate results across runs
        all_results[variant_key] = {
            'name': variant_config['name'],
            'config': variant_config,
            'runs': variant_results,
            'aggregated': aggregate_results(variant_results)
        }

        print(f"\n   ✅ {variant_config['name']} completed!")
        if all_results[variant_key]['aggregated']:
            agg = all_results[variant_key]['aggregated']['overall']
            print(f"   📊 Mean NDCG@10: {agg['NDCG@10']['mean']:.2f}% ± {agg['NDCG@10']['std']:.2f}%")

    return all_results


def aggregate_results(runs_results):
    """Aggregate results across multiple runs"""
    if not runs_results or not runs_results[0]:
        return None

    aggregated = {}

    for split_name in runs_results[0].keys():
        aggregated[split_name] = {}

        for metric in runs_results[0][split_name].keys():
            values = [r[split_name][metric] for r in runs_results if r and split_name in r and metric in r[split_name]]
            if values:
                aggregated[split_name][metric] = {
                    'mean': np.mean(values),
                    'std': np.std(values),
                    'min': np.min(values),
                    'max': np.max(values)
                }

    return aggregated

print("✅ Ablation study functions defined!")

# Run the ablation study
ablation_results = run_ablation_study(
    ABLATION_CONFIGS,
    splits, user_feats, user_item_dict,
    cold_users, n_users, n_items, CONFIG, device,
    n_runs=CONFIG['n_runs']
)

"""## 12. 📊 Results Analysis"""

def print_ablation_results(ablation_results):
    """Print formatted ablation study results"""

    print("\n" + "="*120)
    print("📊 ABLATION STUDY RESULTS")
    print("="*120)

    # Overall results table
    print("\n📈 OVERALL PERFORMANCE (Mean ± Std across runs)")
    print("-"*120)

    header = f"{'Variant':<35} | {'R@10':>12} | {'R@20':>12} | {'R@50':>12} | {'NDCG@10':>12} | {'NDCG@20':>12} | {'NDCG@50':>12}"
    print(header)
    print("-"*120)

    # Sort by NDCG@10
    sorted_variants = sorted(
        ablation_results.items(),
        key=lambda x: x[1]['aggregated']['overall']['NDCG@10']['mean'] if x[1]['aggregated'] else 0,
        reverse=True
    )

    for variant_key, variant_data in sorted_variants:
        if not variant_data['aggregated']:
            continue

        agg = variant_data['aggregated']['overall']
        name = variant_data['name']

        row = f"{name:<35} | "
        for metric in ['R@10', 'R@20', 'R@50', 'NDCG@10', 'NDCG@20', 'NDCG@50']:
            if metric in agg:
                row += f"{agg[metric]['mean']:>5.2f}±{agg[metric]['std']:>4.2f} | "
            else:
                row += f"{'N/A':>12} | "
        print(row)

    print("-"*120)

    # Cold-start specific results
    print("\n❄️ COLD-START PERFORMANCE (Mean ± Std across runs)")
    print("-"*120)
    print(header)
    print("-"*120)

    for variant_key, variant_data in sorted_variants:
        if not variant_data['aggregated'] or 'cold' not in variant_data['aggregated']:
            continue

        agg = variant_data['aggregated']['cold']
        name = variant_data['name']

        row = f"{name:<35} | "
        for metric in ['R@10', 'R@20', 'R@50', 'NDCG@10', 'NDCG@20', 'NDCG@50']:
            if metric in agg:
                row += f"{agg[metric]['mean']:>5.2f}±{agg[metric]['std']:>4.2f} | "
            else:
                row += f"{'N/A':>12} | "
        print(row)

    print("-"*120)

    # Component contribution analysis
    print("\n🔍 COMPONENT CONTRIBUTION ANALYSIS")
    print("-"*80)

    full_ndcg = ablation_results['full']['aggregated']['overall']['NDCG@10']['mean'] if ablation_results.get('full', {}).get('aggregated') else 0

    contributions = []
    for variant_key, variant_data in ablation_results.items():
        if variant_key == 'full' or not variant_data['aggregated']:
            continue

        variant_ndcg = variant_data['aggregated']['overall']['NDCG@10']['mean']
        contribution = full_ndcg - variant_ndcg
        contributions.append((variant_data['name'], contribution, variant_ndcg))

    contributions.sort(key=lambda x: x[1], reverse=True)

    print(f"Full GIFT4Rec NDCG@10: {full_ndcg:.2f}%")
    print("\nComponent contributions (higher = more important):")
    for name, contribution, variant_ndcg in contributions:
        impact = "↓" if contribution > 0 else "↑"
        print(f"   {name:<35}: {impact} {abs(contribution):>5.2f}% (variant: {variant_ndcg:.2f}%)")

print_ablation_results(ablation_results)

"""## 13. 📊 Visualization"""

import matplotlib.pyplot as plt

def plot_ablation_results(ablation_results):
    """Visualize ablation study results"""

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('GIFT4Rec Ablation Study Results', fontsize=16, fontweight='bold')

    # Extract data
    variants = []
    overall_metrics = {'NDCG@10': [], 'NDCG@20': [], 'R@10': [], 'R@20': []}
    cold_metrics = {'NDCG@10': [], 'NDCG@20': [], 'R@10': [], 'R@20': []}
    stds = {'overall': {'NDCG@10': [], 'NDCG@20': [], 'R@10': [], 'R@20': []},
            'cold': {'NDCG@10': [], 'NDCG@20': [], 'R@10': [], 'R@20': []}}

    for variant_key, variant_data in ablation_results.items():
        if not variant_data['aggregated']:
            continue

        variants.append(variant_data['name'].replace('w/o ', '−').replace('Full GIFT4Rec', 'Full'))

        for metric in overall_metrics.keys():
            if metric in variant_data['aggregated']['overall']:
                overall_metrics[metric].append(variant_data['aggregated']['overall'][metric]['mean'])
                stds['overall'][metric].append(variant_data['aggregated']['overall'][metric]['std'])
            else:
                overall_metrics[metric].append(0)
                stds['overall'][metric].append(0)

            if 'cold' in variant_data['aggregated'] and metric in variant_data['aggregated']['cold']:
                cold_metrics[metric].append(variant_data['aggregated']['cold'][metric]['mean'])
                stds['cold'][metric].append(variant_data['aggregated']['cold'][metric]['std'])
            else:
                cold_metrics[metric].append(0)
                stds['cold'][metric].append(0)

    x = np.arange(len(variants))
    width = 0.35

    # Plot 1: Overall NDCG comparison
    ax1 = axes[0, 0]
    bars1 = ax1.bar(x - width/2, overall_metrics['NDCG@10'], width, label='NDCG@10',
                    yerr=stds['overall']['NDCG@10'], capsize=3, color='steelblue')
    bars2 = ax1.bar(x + width/2, overall_metrics['NDCG@20'], width, label='NDCG@20',
                    yerr=stds['overall']['NDCG@20'], capsize=3, color='lightsteelblue')
    ax1.set_ylabel('NDCG (%)')
    ax1.set_title('Overall NDCG Performance')
    ax1.set_xticks(x)
    ax1.set_xticklabels(variants, rotation=45, ha='right')
    ax1.legend()
    ax1.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot 2: Overall Recall comparison
    ax2 = axes[0, 1]
    bars3 = ax2.bar(x - width/2, overall_metrics['R@10'], width, label='R@10',
                    yerr=stds['overall']['R@10'], capsize=3, color='coral')
    bars4 = ax2.bar(x + width/2, overall_metrics['R@20'], width, label='R@20',
                    yerr=stds['overall']['R@20'], capsize=3, color='lightsalmon')
    ax2.set_ylabel('Recall (%)')
    ax2.set_title('Overall Recall Performance')
    ax2.set_xticks(x)
    ax2.set_xticklabels(variants, rotation=45, ha='right')
    ax2.legend()
    ax2.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot 3: Cold-start NDCG comparison
    ax3 = axes[1, 0]
    bars5 = ax3.bar(x - width/2, cold_metrics['NDCG@10'], width, label='NDCG@10',
                    yerr=stds['cold']['NDCG@10'], capsize=3, color='darkgreen')
    bars6 = ax3.bar(x + width/2, cold_metrics['NDCG@20'], width, label='NDCG@20',
                    yerr=stds['cold']['NDCG@20'], capsize=3, color='lightgreen')
    ax3.set_ylabel('NDCG (%)')
    ax3.set_title('Cold-Start NDCG Performance')
    ax3.set_xticks(x)
    ax3.set_xticklabels(variants, rotation=45, ha='right')
    ax3.legend()
    ax3.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot 4: Component contribution
    ax4 = axes[1, 1]
    full_ndcg = ablation_results['full']['aggregated']['overall']['NDCG@10']['mean'] if ablation_results.get('full', {}).get('aggregated') else 0

    contributions = []
    contrib_names = []
    for variant_key, variant_data in ablation_results.items():
        if variant_key == 'full' or not variant_data['aggregated']:
            continue
        variant_ndcg = variant_data['aggregated']['overall']['NDCG@10']['mean']
        contributions.append(full_ndcg - variant_ndcg)
        contrib_names.append(variant_data['name'].replace('w/o ', '').replace('(α=0.5)', '').strip())

    colors = ['green' if c > 0 else 'red' for c in contributions]
    ax4.barh(contrib_names, contributions, color=colors, alpha=0.7)
    ax4.axvline(x=0, color='black', linestyle='-', linewidth=0.5)
    ax4.set_xlabel('Contribution to NDCG@10 (%)')
    ax4.set_title('Component Contribution (Positive = Important)')
    ax4.grid(axis='x', linestyle='--', alpha=0.7)

    plt.tight_layout()
    plt.savefig('ablation_results.png', dpi=300, bbox_inches='tight')
    plt.show()

    print("\n✅ Results saved to 'ablation_results.png'")

plot_ablation_results(ablation_results)

"""## 14. 💾 Save Results"""

def save_results(ablation_results, filename='ablation_results.json'):
    """Save results to JSON file"""

    # Convert to serializable format
    serializable_results = {}

    for variant_key, variant_data in ablation_results.items():
        serializable_results[variant_key] = {
            'name': variant_data['name'],
            'config': variant_data['config'],
            'aggregated': variant_data['aggregated']
        }

    with open(filename, 'w') as f:
        json.dump(serializable_results, f, indent=2)

    print(f"✅ Results saved to '{filename}'")

save_results(ablation_results)

# Create summary table for paper
def create_latex_table(ablation_results):
    """Create LaTeX table for paper"""

    print("\n📝 LaTeX Table for Paper:")
    print("="*80)

    print(r"\begin{table}[h]")
    print(r"\centering")
    print(r"\caption{Ablation Study Results on MovieLens-1M}")
    print(r"\label{tab:ablation}")
    print(r"\begin{tabular}{l|ccc|ccc}")
    print(r"\hline")
    print(r"\multirow{2}{*}{Variant} & \multicolumn{3}{c|}{Overall} & \multicolumn{3}{c}{Cold-Start} \\")
    print(r"& R@10 & R@20 & NDCG@10 & R@10 & R@20 & NDCG@10 \\")
    print(r"\hline")

    # Sort by overall NDCG@10
    sorted_variants = sorted(
        ablation_results.items(),
        key=lambda x: x[1]['aggregated']['overall']['NDCG@10']['mean'] if x[1]['aggregated'] else 0,
        reverse=True
    )

    for variant_key, variant_data in sorted_variants:
        if not variant_data['aggregated']:
            continue

        name = variant_data['name'].replace('_', '\_')
        agg_overall = variant_data['aggregated']['overall']
        agg_cold = variant_data['aggregated'].get('cold', {})

        # Bold for best (full model)
        if variant_key == 'full':
            name = r"\textbf{" + name + "}"

        row = f"{name} & "

        for metric in ['R@10', 'R@20', 'NDCG@10']:
            if metric in agg_overall:
                val = f"{agg_overall[metric]['mean']:.2f}"
                if variant_key == 'full':
                    val = r"\textbf{" + val + "}"
                row += val + " & "
            else:
                row += "- & "

        for metric in ['R@10', 'R@20', 'NDCG@10']:
            if metric in agg_cold:
                val = f"{agg_cold[metric]['mean']:.2f}"
                if variant_key == 'full':
                    val = r"\textbf{" + val + "}"
                row += val
                if metric != 'NDCG@10':
                    row += " & "
            else:
                row += "-"
                if metric != 'NDCG@10':
                    row += " & "

        print(row + r" \\")

    print(r"\hline")
    print(r"\end{tabular}")
    print(r"\end{table}")

create_latex_table(ablation_results)

"""## 15. 📋 Summary"""

print("\n" + "="*100)
print("🎯 ABLATION STUDY SUMMARY")
print("="*100)

print("\n📊 Key Findings:")
print("-"*80)

if ablation_results:
    full_results = ablation_results.get('full', {}).get('aggregated', {})

    if full_results:
        print(f"\n1. Full GIFT4Rec achieves best performance:")
        print(f"   - Overall NDCG@10: {full_results['overall']['NDCG@10']['mean']:.2f}% ± {full_results['overall']['NDCG@10']['std']:.2f}%")
        if 'cold' in full_results:
            print(f"   - Cold-Start NDCG@10: {full_results['cold']['NDCG@10']['mean']:.2f}% ± {full_results['cold']['NDCG@10']['std']:.2f}%")

    # Find most important component
    full_ndcg = full_results['overall']['NDCG@10']['mean'] if full_results else 0
    max_drop = 0
    most_important = ""

    for key, data in ablation_results.items():
        if key == 'full' or not data.get('aggregated'):
            continue
        drop = full_ndcg - data['aggregated']['overall']['NDCG@10']['mean']
        if drop > max_drop:
            max_drop = drop
            most_important = data['name']

    print(f"\n2. Most important component: {most_important}")
    print(f"   - Removing it causes {max_drop:.2f}% drop in NDCG@10")

    print("\n3. Component importance ranking:")
    contributions = []
    for key, data in ablation_results.items():
        if key == 'full' or not data.get('aggregated'):
            continue
        drop = full_ndcg - data['aggregated']['overall']['NDCG@10']['mean']
        contributions.append((data['name'], drop))

    contributions.sort(key=lambda x: x[1], reverse=True)
    for i, (name, drop) in enumerate(contributions, 1):
        print(f"   {i}. {name}: Δ={drop:+.2f}%")

print("\n" + "="*100)
print("✅ Ablation Study Complete!")
print("="*100)